feed_dog:
  description: Füttert den Hund und aktualisiert die Fütterungsstatistiken.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    meal_type:
      description: Art der Mahlzeit
      example: "morning"
      default: "morning"
      selector:
        select:
          options:
            - "morning"
            - "lunch"
            - "evening"
            - "snack"
    amount:
      description: Futtermenge in Gramm
      example: 200
      default: 100
      selector:
        number:
          min: 10
          max: 1000
          step: 10
          unit_of_measurement: "g"

walk_dog:
  description: Zeichnet einen Spaziergang auf.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    duration:
      description: Dauer des Spaziergangs in Minuten
      example: 30
      default: 30
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: "min"
    distance:
      description: Zurückgelegte Distanz in Kilometern
      example: "2.5"
      selector:
        text:
    notes:
      description: Notizen zum Spaziergang
      selector:
        text:
          multiline: true
    weather:
      description: Wetterbedingungen
      selector:
        text:

play_with_dog:
  description: Zeichnet eine Spielsession auf.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    duration:
      description: Dauer des Spielens in Minuten
      example: 15
      default: 15
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: "min"
    play_type:
      description: Art des Spiels
      selector:
        text:
    intensity:
      description: Intensität der Session
      selector:
        text:
    notes:
      description: Notizen
      selector:
        text:
          multiline: true

activate_emergency_mode:
  description: Aktiviert den Notfallmodus.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    reason:
      description: Grund für den Notfallmodus
      selector:
        text:
          multiline: true

toggle_visitor_mode:
  description: Schaltet den Besuchermodus um.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:

perform_health_check:
  description: Führt einen Gesundheitscheck durch.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    temperature:
      description: Körpertemperatur in °C
      example: 38.5
      selector:
        number:
          min: 35.0
          max: 42.0
          step: 0.1
          unit_of_measurement: "°C"
    weight:
      description: Aktuelles Gewicht in kg
      example: 25.5
      selector:
        number:
          min: 0.5
          max: 100.0
          step: 0.1
          unit_of_measurement: "kg"
    notes:
      description: Gesundheitsnotizen
      example: "Allgemein guter Zustand"
      selector:
        text:
          multiline: true

mark_medication_given:
  description: Markiert Medikamente als gegeben.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    medication:
      description: Name des Medikaments
      selector:
        text:
    dosage:
      description: Dosierung
      selector:
        text:
    notes:
      description: Notizen
      selector:
        text:
          multiline: true

start_grooming_session:
  description: Zeichnet eine Pflegesession auf.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    grooming_type:
      description: Art der Pflege
      selector:
        text:
    duration:
      description: Dauer in Minuten
      example: 30
      default: 30
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: "min"
    professional:
      description: Wird professionell durchgeführt
      selector:
        boolean:
    notes:
      description: Notizen
      selector:
        text:
          multiline: true

start_training_session:
  description: Zeichnet eine Trainingseinheit auf.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    training_type:
      description: Art des Trainings
      selector:
        text:
    duration:
      description: Dauer in Minuten
      example: 10
      default: 10
      selector:
        number:
          min: 1
          max: 300
          step: 1
          unit_of_measurement: "min"
    commands:
      description: Geübte Kommandos
      selector:
        text:
    success_rate:
      description: Erfolgsquote
      selector:
        text:
    notes:
      description: Notizen
      selector:
        text:
          multiline: true

record_vet_visit:
  description: Protokolliert einen Tierarztbesuch.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    visit_type:
      description: Art des Besuchs
      selector:
        text:
    diagnosis:
      description: Diagnose
      selector:
        text:
    treatment:
      description: Behandlung
      selector:
        text:
    next_appointment:
      description: Nächster Termin
      selector:
        text:
    cost:
      description: Kosten
      selector:
        text:
    notes:
      description: Notizen
      selector:
        text:
          multiline: true

generate_report:
  description: Generiert einen Installationsbericht.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:

update_gps:
  description: Aktualisiert die GPS-Position des Hundes.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    latitude:
      description: GPS Breitengrad
      example: 52.233333
      required: true
      selector:
        number:
          min: -90
          max: 90
          step: 0.000001
    longitude:
      description: GPS Längengrad
      example: 8.966667
      required: true
      selector:
        number:
          min: -180
          max: 180
          step: 0.000001
    accuracy:
      description: GPS Genauigkeit in Metern
      example: 10
      default: 10
      selector:
        number:
          min: 1
          max: 1000
          step: 1
          unit_of_measurement: "m"

daily_reset:
  description: Setzt alle täglichen Daten zurück.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:

start_walk_tracking:
  description: Startet das GPS-Tracking eines Spaziergangs.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
    walk_name:
      description: Optionaler Name des Spaziergangs
      example: "Abendrunde"
      selector:
        text:

end_walk_tracking:
  description: Beendet das GPS-Tracking und aktualisiert die Statistiken.
  fields:
    dog_name:
      description: Name des Hundes
      example: "buddy"
      required: true
      selector:
        text:
